# Generated by Django 5.1 on 2024-08-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelesAcademicos',
            fields=[
                ('id_nivel_academico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_nivel_academico', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('cod_estudiante', models.CharField(max_length=9, null=True)),
                ('nombres_estudiante', models.CharField(max_length=100, null=True)),
                ('apellidos_estudiante', models.CharField(max_length=100, null=True)),
                ('anio_ingreso', models.CharField(max_length=100, null=True)),
                ('estado_estudiante', models.IntegerField(default=1)),
                ('perfil_estudiante', models.CharField(max_length=100, null=True)),
                ('captura_biometrica', models.CharField(max_length=255, null=True)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.especialidades')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facultades')),
                ('id_nivel_academico', models.ForeignKey(db_column='id_nivel_academico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nivelesacademicos')),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaIngresos',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('hora_ingreso', models.TimeField(auto_now_add=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alerta', models.DateField(auto_now_add=True)),
                ('hora_alerta', models.TimeField(auto_now_add=True)),
                ('detalle_alerta', models.CharField(max_length=255, null=True)),
                ('estado_alerta', models.IntegerField(default=1)),
                ('foto_captura', models.CharField(max_length=255, null=True)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='especialidades',
            name='id_facultad',
            field=models.ForeignKey(db_column='id_facultad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facultades'),
        ),
        migrations.AddField(
            model_name='especialidades',
            name='id_nivel_academico',
            field=models.ForeignKey(db_column='id_nivel_academico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nivelesacademicos'),
        ),
        migrations.CreateModel(
            name='EnvioAlertas',
            fields=[
                ('id_envio_alertas', models.AutoField(primary_key=True, serialize=False)),
                ('id_alerta', models.ForeignKey(db_column='id_alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.alertas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuarios')),
            ],
        ),
    ]
