# Generated by Django 5.1 on 2024-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewEstudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('cod_estudiante', models.CharField(max_length=9, null=True)),
                ('nombres_estudiante', models.CharField(max_length=100, null=True)),
                ('apellidos_estudiante', models.CharField(max_length=100, null=True)),
                ('anio_ingreso', models.CharField(max_length=100, null=True)),
                ('estado_estudiante', models.IntegerField(default=1)),
                ('perfil_estudiante', models.CharField(max_length=100, null=True)),
                ('captura_biometrica', models.CharField(max_length=255, null=True)),
                ('nombre_nivel_academico', models.CharField(max_length=100, null=True)),
                ('nombre_facultad', models.CharField(max_length=100, null=True)),
                ('nombre_especialidad', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'view_estudiantes',
                'managed': False,
            },
        ),
    ]
